#!groovy
// void setBuildStatus(String message, String state) {
//   step([
//       $class: "GitHubCommitStatusSetter",
//       reposSource: [$class: "ManuallyEnteredRepositorySource", url: "$env.GIT_URL"],
//       contextSource: [$class: "ManuallyEnteredCommitContextSource", context: "ci/jenkins/build-status"],
//       errorHandlers: [[$class: "ChangingBuildStatusErrorHandler", result: "UNSTABLE"]],
//       statusResultSource: [ $class: "ConditionalStatusResultSource", results: [[$class: "AnyBuildResult", message: message, state: state]] ]
//   ]);
// }

pipeline {
    agent { label 'master-runner' }
    environment {
        webhook_key = credentials('webhook_key')
    }
    // environment {
    //     webhook_key = credentials('webhook_key')
    // }

    stages {
        stage('Unit Test') {
            steps {
                echo 'Unit test'
            }
        }
        stage('Code Build') {
            when {
                branch 'master'
            }
            steps {
                echo 'Code Building'
            }
        }
    }
    post {
    success {
        script {
                    sh(script: 'bash jenkins/post.sh success')
            }
  }
}